config/routes.rb
Rails.application.routes.draw do
  resources :songs, param: :slug
end

app/models/song.rb
class Song < ActiveRecord::Base
  before_save :set_slug

  private

    def set_slug
      self.slug = title.parameterize
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :load_song, only: [:show, :edit, :update, :destroy]

  def index
    @songs = Song.all
  end

  def show
  end

  def new
    @song = Song.new
  end

  def create
    Song.create(song_params)
    redirect_to songs_path
  end

  def edit
  end

  def update
    if @song.update(song_params)
      redirect_to songs_path
    else
      render :edit
    end
  end

  def destroy
    @song.delete
    redirect_to songs_path
  end

  private

    def song_params
      params.require(:song).permit(:title, :artist)
    end

    def load_song
      @song = Song.find_by(slug: params[:slug])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyJams</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/songs/edit.html.erb
<%= form_for @song do |f| %>
  <%= f.text_field :title %>
  <%= f.text_field :artist %>
  <%= f.submit %>
<% end %>

app/views/songs/index.html.erb
<h1>Song List</h1>

<%= link_to "Create Song", new_song_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Artist</th>
    <th>Slug</th>
    <th>Actions</th>
  </tr>
  <% @songs.each do |song| %>
    <tr>
      <td><%= link_to song.title, song_path(song.slug) %></td>
      <td><%= song.artist %></td>
      <td><%= song.slug %></td>
      <td>
        <%= link_to "Edit", edit_song_path(song.slug) %> | 
        <%= link_to "Destroy", song_path(song.slug), method: :delete %>
      </td>
    </tr>
  <% end %>
</table>

app/views/songs/new.html.erb
<%= form_for @song do |f| %>
  <%= f.text_field :title %>
  <%= f.text_field :artist %>
  <%= f.submit %>
<% end %>

app/views/songs/show.html.erb
<strong>Song:</strong> <%= @song.title %><br>
<strong>Artist:</strong> <%= @song.artist %>